### ISSUE TITLE
draggable within another draggable

### ISSUE THREAD

**Issue by mukeshsoni** [mzabriskie/react-draggable#11]
I have a use case where one draggable can be within another draggable and so on. I have positioned the elements as 'absolute'. When i move a child draggable element, the parents left+top are also changed and it moves too. I have also tried attaching handles for each element (by class name), but to no affect. Is it possible to move the child element independently?

**Comment by brianfay** [comment]
For anbody reading this who is trying to drag one Draggable component inside another without moving both, you can implement handleStart like this:
<code>
handleStart(e, ui){
  e.stopPropagation();
}
</code>
That will stop the drag event from bubbling up to the parent, so that the child can be moved independently from the parent.

**Comment by AlexChaseJones** [comment]
anyone endinging up here; the new method is called `onStart`
