### ISSUE TITLE
Ractify missing from dependencies

### ISSUE THREAD

**Issue by lmb** [mzabriskie/react-draggable#15]
First of all, thanks for your work on the component.
When using the component with browserify it complains about reactify not being installed. Adding it to the package.json dependencies should fix that?

**Comment by jtremback** [comment]
Reactify does not work in dev-dependencies. It needs to be installed in dependencies, because dev-dependencies are only installed at the top layer. Adding it to dev-dependencies does nothing, in my project.

This is not a pressing issue for me, as I have simply included reactify in my dev-dependencies. I think this is really more browserify's fault.
